# Generated by https://quicktype.io

from typing import List


class Address:
    street_address: List[str]
    city: List[str]
    state: List[str]
    postal_code: List[int]

    def __init__(self, street_address: List[str], city: List[str], state: List[str], postal_code: List[int]) -> None:
        self.street_address = street_address
        self.city = city
        self.state = state
        self.postal_code = postal_code


class PhoneNumberPhoneNumber:
    type: List[str]
    number: List[str]

    def __init__(self, type: List[str], number: List[str]) -> None:
        self.type = type
        self.number = number


class PersonPhoneNumber:
    phone_number: List[PhoneNumberPhoneNumber]

    def __init__(self, phone_number: List[PhoneNumberPhoneNumber]) -> None:
        self.phone_number = phone_number


class Sex:
    type: List[str]

    def __init__(self, type: List[str]) -> None:
        self.type = type


class PersonClass:
    first_name: List[str]
    last_name: List[str]
    age: List[int]
    address: List[Address]
    phone_numbers: List[PersonPhoneNumber]
    sex: List[Sex]

    
    def __init__(self, first_name: List[str], last_name: List[str], age: List[int], address: List[Address], phone_numbers: List[PersonPhoneNumber], sex: List[Sex]) -> None:
        self.first_name = first_name
        self.last_name = last_name
        self.age = age
        self.address = address
        self.phone_numbers = phone_numbers
        self.sex = sex


class Person:
    person: PersonClass

    def __init__(self, person: PersonClass) -> None:
        self.person = person
